[phases.setup]
nixPkgs = ["nodejs_22", "nginx"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "mkdir -p /etc/nginx/conf.d && cp /app/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
