
# This file is not really needed anymore but left it as an example just incase need more config in the future
[phases.setup]
nixPkgs = ["nodejs_22", "nginx"]

# Do not do npm install because Dokploy will run it twice
[phases.build]
cmds = ["npm run build"]

# daemon off ensures the server runs in the foreground and does not stop and also gives us logging
[start]
cmd = "nginx -g 'daemon off;'"
